### ISSUE TITLE
Missing song lists

### ISSUE THREAD

**Issue by ddools** [RaduFi/gMusic#1]
Hey. love gMusic. excellent work.

but just wondering has anybody else reported a problem where the song list is missing?
all i see is the rotating artist image in the background ?

Images/screenshots: http://imgur.com/a/6ygB4

**Comment by raduflp** [comment]
Hey, thanks for reporting the issue. Google keeps changing their design, but I have fixed it in the latest version.
Cheers

**Comment by ddools** [comment]
Excellent. Keep up the great work!
